CC=g++
CFLAGS= -std=c++11 -w

all:Calculator LinkedStack
	$(CC) $(CFLAGS) -o Calculator.exe Calculator.o LinkedStack.o 
	
Calculator:Calculator.cpp
	$(CC) $(CFLAGS) -c Calculator.cpp
	
LinkedStack:LinkedStack.cpp
	$(CC) $(CFLAGS) -c LinkedStack.cpp 